### ISSUE TITLE
Interop problem with scalajs-react

### ISSUE THREAD

**Issue by NightMachinary** [shadaj/slinky#146]
```
package me.freidoon.serenity

import slinky.core._
import slinky.core.annotations.react
import slinky.web.html._

import scala.scalajs.js
import scala.scalajs.js.annotation.{JSImport, ScalaJSDefined}

@JSImport("resources/App.css", JSImport.Default)
@js.native
object AppCSS extends js.Object

@JSImport("resources/logo.svg", JSImport.Default)
@js.native
object ReactLogo extends js.Object

@react class App extends StatelessComponent {
  type Props = Unit

  private val css = AppCSS

  def render() = {
    div(className := "App")(
      header(className := "App-header")(
        img(src := ReactLogo.asInstanceOf[String], className := "App-logo", alt := "logo"),
        h1(className := "App-title")("Welcome to React (with Scala.js!)")
      ),
      p(className := "App-intro")(
        "To get started, edit ", code("App.scala"), " and save to reload."
      )
    )
    div(className := "Center-container")(header("serenity"),
        p("this is Fereidoon's react-based static website."))
  }
}
```

```
package me.freidoon.serenity

import japgolly.scalajs.react.vdom.html_<^._
import japgolly.scalajs.react.extra.router._

import scala.scalajs.js
import scala.scalajs.js.annotation.{JSExportTopLevel, JSImport}
import scala.scalajs.LinkingInfo

import slinky.core._
import slinky.web.ReactDOM
import slinky.hot

import org.scalajs.dom
import slinky.scalajsreact.Converters._

@JSImport("resources/index.css", JSImport.Default)
@js.native
object IndexCSS extends js.Object

object Main {
  val css = IndexCSS

  sealed trait MyPages
  case object Hello                      extends MyPages
  case object Home                      extends MyPages
  case object Search                    extends MyPages
  case object Products                  extends MyPages
  case class ProductInfo(id: Int) extends MyPages

  @JSExportTopLevel("entrypoint.main")
  def main(): Unit = {
    if (LinkingInfo.developmentMode) {
      hot.initialize()
    }

    val routerConfig = RouterConfigDsl[MyPages].buildConfig { dsl =>
      import dsl._

      (emptyRule
         | staticRoute(root,     Home)  ~> render(<.div("Root","lol",App()))
         | staticRoute("#hello", Hello) ~> render(<.div("TODO"))
      ) .notFound(redirectToPage(Home)(Redirect.Push))
    }
    val router = Router(BaseUrl.fromWindowOrigin, routerConfig)
    // tell React to render the router in the document body
    router().renderIntoDOM(dom.document.getElementById("root"))

    return

    val container = Option(dom.document.getElementById("root")).getOrElse {
      val elem = dom.document.createElement("div")
      elem.id = "root"
      dom.document.body.appendChild(elem)
      elem
    }

    ReactDOM.render(App(), container)
  }
}
```

This will result in the following exception:
```

react-dom.development.js:12431 Uncaught 
$c_sjsr_UndefinedBehaviorError
e$1
:
$c_jl_ClassCastException {s$1: "undefined is not an instance of java.lang.String", e$1: null, stackTrace$1: null, stackdata: $c_jl_ClassCastException, stack: "Error↵    at $c_jl_ClassCastException.appLibrary..…/localhost:8080/dependencies-library.js:17898:12)"}
s$1
:
"An undefined behavior was detected: undefined is not an instance of java.lang.String"
stackTrace$1
:
null
stackdata
:
$c_sjsr_UndefinedBehaviorError {s$1: "An undefined behavior was detected: undefined is not an instance of java.lang.String", e$1: $c_jl_ClassCastException, stackTrace$1: null, stackdata: $c_sjsr_UndefinedBehaviorError, stack: "Error↵    at $c_sjsr_UndefinedBehaviorError.appLib…/localhost:8080/dependencies-library.js:26656:30)"}
stack
:
"Error↵    at $c_sjsr_UndefinedBehaviorError.appLibrary../serenity-fastopt.js.$c_jl_Throwable.fillInStackTrace__jl_Throwable (http://localhost:8080/serenity-fastopt-library.js:19549:14)↵    at $c_sjsr_UndefinedBehaviorError.appLibrary../serenity-fastopt.js.$c_sjsr_UndefinedBehaviorError.fillInStackTrace__jl_Throwable (http://localhost:8080/serenity-fastopt-library.js:29992:67)↵    at $c_sjsr_UndefinedBehaviorError.appLibrary../serenity-fastopt.js.$c_jl_Throwable.init___T__jl_Throwable (http://localhost:8080/serenity-fastopt-library.js:19565:8)↵    at $c_sjsr_UndefinedBehaviorError.appLibrary../serenity-fastopt.js.$c_sjsr_UndefinedBehaviorError.init___T__jl_Throwable (http://localhost:8080/serenity-fastopt-library.js:29999:52)↵    at $c_sjsr_UndefinedBehaviorError.appLibrary../serenity-fastopt.js.$c_sjsr_UndefinedBehaviorError.init___jl_Throwable (http://localhost:8080/serenity-fastopt-library.js:29995:67)↵    at $throwClassCastException (http://localhost:8080/serenity-fastopt-library.js:10343:46)↵    at $as_T (http://localhost:8080/serenity-fastopt-library.js:24002:50)↵    at $s_Lme_freidoon_serenity_App__render__Lme_freidoon_serenity_App__Lslinky_core_facade_ReactElement (http://localhost:8080/serenity-fastopt-library.js:25679:80)↵    at $c_Lme_freidoon_serenity_App.render (http://localhost:8080/serenity-fastopt-library.js:25889:14)↵    at $c_Lme_freidoon_serenity_App.proxiedMethod [as render] (http://localhost:8080/dependencies-library.js:26656:30)"
__proto__
:
$c_jl_Error
```

PS: Is there no native way to use routers with slinky?

**Comment by NightMachinary** [comment]
I have confirmed that the problem appears merely by having the interop library added to dependencies.
And it seems I can just use React Router :)

**Comment by shadaj** [comment]
@NightMachinary thanks for the bug report!

Yes, one of the core features of Slinky is that you are free to use existing React libraries like React Router! 😃

**Comment by shadaj** [comment]
@NightMachinary I just tried to reproduce locally, and I'm not seeing the error. What version of Scala.js React are you using?

**Comment by shadaj** [comment]
@NightMachinary I updated the Scala.js React version for interop in 0.4.3. Can you see if you're still encountering the same errors?

**Comment by NightMachinary** [comment]
@shadaj Things are certainly better with 0.4.3, but I still get this error when I mix Slinky and scala-js:
```
[info] Compiling 5 Scala sources to /Base/- Code/Scala/serenity/target/scala-2.12/classes ...
[error] <macro>:8:19: not found: type ReactElement
[error]     def render(): ReactElement = ScalajsReactComponent(props.name)
[error]                   ^
[error] /Base/- Code/Scala/serenity/src/main/scala/me/freidoon/serenity/package.scala:19:30: type mismatch;
[error]  found   : japgolly.scalajs.react.vdom.TagOf[org.scalajs.dom.html.Div]
[error]     (which expands to)  japgolly.scalajs.react.vdom.TagOf[org.scalajs.dom.raw.HTMLDivElement]
[error]  required: japgolly.scalajs.react.vdom.VdomNode
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method vdomElementFromTag in trait ImplicitsForVdomElement of type [A](a: A)(implicit f: A => japgolly.scalajs.react.vdom.Exports.VdomTag)japgolly.scalajs.react.vdom.VdomElement
[error]  and method componentInstanceToVdom in object Converters of type [T](component: T)(implicit ev: T => slinky.core.facade.ReactElement)japgolly.scalajs.react.vdom.VdomNode
[error]  are possible conversion functions from japgolly.scalajs.react.vdom.TagOf[org.scalajs.dom.html.Div] to japgolly.scalajs.react.vdom.VdomNode
[error]       .render_P(name => <.div( // a scalajs-react tag here
[error]                              ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Jun 13, 2018 5:27:29 PM
```

Source:
```
package me.freidoon
import slinky.core._
import slinky.core.annotations.react
import slinky.web.html._

import slinky.scalajsreact.Converters._


import japgolly.scalajs.react._

import japgolly.scalajs.react.vdom.html_<^._
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSImport, ScalaJSDefined}

package object serenity {
  val CssSettings = scalacss.devOrProdDefaults
  val ScalajsReactComponent =
    ScalaComponent.builder[String]("Hello")
      .render_P(name => <.div( // a scalajs-react tag here
                  "Hello, ", name,
                  "This is a component from scalajs-react",
                  div( // a Slinky tag being used here
                    "and this is from Slinky inside the scalajs-react component!"
                  )
                ))
      .build

}

```

**Comment by shadaj** [comment]
This is fixed with the explicit conversion required in v0.5.0!
