### ISSUE TITLE
IntelliJ support broken in 2019.2 EAP

### ISSUE THREAD

**Issue by nafg** [shadaj/slinky#276]
IntelliJ build #IU-192.4205.45, scala plugin 2019.2.234

<details>
<summary>Stack trace</summary>
<pre>
java.lang.NoSuchMethodError: org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes$Map.forName(Ljava/lang/String;)Lscala/Tuple2;
	at slinky.core.SlinkyInjector.createComponentBody(SlinkyInjector.scala:22)
	at slinky.core.SlinkyInjector.injectMembers(SlinkyInjector.scala:243)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$injectMembers$1(SyntheticMembersInjector.scala:174)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.$anonfun$injectMembers$1$adapted(SyntheticMembersInjector.scala:173)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:319)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:975)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.SyntheticMembersInjector$.injectMembers(SyntheticMembersInjector.scala:173)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTypeDefinition.syntheticMembersImpl(ScTypeDefinition.scala:68)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTypeDefinition.syntheticMembersImpl$(ScTypeDefinition.scala:68)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticMembersImpl(ScTypeDefinitionImpl.scala:51)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition.syntheticMembers(ScTemplateDefinition.scala:180)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition.syntheticMembers$(ScTemplateDefinition.scala:179)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.ScTypeDefinitionImpl.syntheticMembers(ScTypeDefinitionImpl.scala:51)
	at org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTemplateDefinition$SyntheticMembersExt$.membersWithSynthetic$extension(ScTemplateDefinition.scala:544)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$SignatureNodes$.relevantMembers(TypeDefinitionMembers.scala:69)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$SignatureNodes.processScala(TypeDefinitionMembers.scala:128)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.addAllFrom(MixinNodes.scala:97)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.$anonfun$build$1(MixinNodes.scala:62)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.MixinNodes.build(MixinNodes.scala:58)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.$anonfun$forTopLevelClasses$1(ScalaPsiManager.scala:343)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(Unknown Source)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.forTopLevelClasses(ScalaPsiManager.scala:343)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager$SignatureCaches.cachedMap(ScalaPsiManager.scala:354)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers$.getSignatures(TypeDefinitionMembers.scala:200)
	at org.jetbrains.plugins.scala.lang.psi.light.PsiClassWrapper.psiMethods(PsiClassWrapper.scala:84)
	at org.jetbrains.plugins.scala.lang.psi.adapters.PsiClassAdapter.getMethods(PsiClassAdapter.java:31)
	at org.jetbrains.plugins.scala.lang.psi.light.PsiClassWrapper.getMethods(PsiClassWrapper.scala:36)
	at com.intellij.psi.impl.PsiClassImplUtil.processDeclarationsInClassNotCached(PsiClassImplUtil.java:667)
	at com.intellij.psi.impl.PsiClassImplUtil.lambda$createMembersMap$2(PsiClassImplUtil.java:382)
	at com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:46)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.get(PsiClassImplUtil.java:344)
	at com.intellij.psi.impl.PsiClassImplUtil$MembersMap.access$000(PsiClassImplUtil.java:336)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:194)
	at com.intellij.psi.impl.PsiClassImplUtil.findByMap(PsiClassImplUtil.java:140)
	at com.intellij.psi.impl.PsiClassImplUtil.findMethodsByName(PsiClassImplUtil.java:83)
	at org.jetbrains.plugins.scala.lang.psi.light.PsiClassWrapper.findMethodsByName(PsiClassWrapper.scala:174)
	at com.intellij.psi.util.PsiMethodUtil.findMainMethod(PsiMethodUtil.java:33)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.$anonfun$findMainMethod$5(ScalaApplicationConfigurationProducer.scala:154)
	at scala.Option.orElse(Option.scala:289)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.findMainMethodInner$1(ScalaApplicationConfigurationProducer.scala:154)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.findMainMethod(ScalaApplicationConfigurationProducer.scala:158)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodProvider.$anonfun$findMainInClass$1(ScalaMainMethodProvider.scala:21)
	at scala.Option.flatMap(Option.scala:171)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodProvider.findMainInClass(ScalaMainMethodProvider.scala:20)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodProvider.hasMainMethod(ScalaMainMethodProvider.scala:27)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.$anonfun$hasMainMethodFromProviders$1(ScalaApplicationConfigurationProducer.scala:133)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.$anonfun$hasMainMethodFromProviders$1$adapted(ScalaApplicationConfigurationProducer.scala:133)
	at scala.collection.IndexedSeqOptimized.prefixLengthImpl(IndexedSeqOptimized.scala:37)
	at scala.collection.IndexedSeqOptimized.exists(IndexedSeqOptimized.scala:45)
	at scala.collection.IndexedSeqOptimized.exists$(IndexedSeqOptimized.scala:45)
	at scala.collection.mutable.ArrayOps$ofRef.exists(ArrayOps.scala:194)
	at org.jetbrains.plugins.scala.runner.ScalaMainMethodUtil$.hasMainMethodFromProviders(ScalaApplicationConfigurationProducer.scala:133)
	at org.jetbrains.plugins.scala.runner.ScalaRunLineMarkerContributor.getInfo(ScalaRunLineMarkerContributor.scala:21)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:171)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:79)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:231)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:173)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
</pre>
</details>

**Comment by shadaj** [comment]
@nafg do you know when 2019.2 is expected to be released? I have a feeling that any fix I make for 2019.2 will probably break 2019.1, so want to tread carefully with fixing this.

**Comment by nafg** [comment]
Well at least you can test that because 2019.1 is not a moving target...

I have no idea when they plan to release but to if I were to take a guess,
they've already released a few EAPs for it, so I'd imagine they would be at
RC within a month... that's just a guess, I don't remember clearly previous
timelines for certain.

**Comment by evbo** [comment]
I just installed `idea-IC-192.5728.98` along with the latest scala plugin and can confirm slinky works just as well as it did for 2019.1!

Not sure if we want to do specific tests, but I see nothing broken and my app utilizes slinky `0.6.2` features including support for react hooks

**Comment by ingarabr** [comment]
The same exception is showing up in my logs.

I'm using:
- IntelliJ IDEA 2019.2.3  Build #IU-192.6817.14
- Scala plugin version: 2019.2.1144
