### ISSUE TITLE
Project import failed, Intellij IDEA 2020.1, 

### ISSUE THREAD

**Issue by basicobject** [shadaj/slinky#359]
It seems the Intellij IDEA support is broken for 2020.1 CE.

I am not sure what is wrong here, import consistenly fails for me.

```
[IJ]sbt:slinky> last coreIntellijSupport / intellijPluginJars
[error] Cannot find bundled plugin root for folder name: java
[error] java.nio.file.NoSuchFileException: /Users/deepakkumar/.slinkyPluginIC/sdk/192.6817.14/plugins
[error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[error] 	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
[error] 	at java.nio.file.Files.newDirectoryStream(Files.java:457)
[error] 	at java.nio.file.Files.list(Files.java:3451)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginIndexImpl.buildFromPluginsDir(PluginIndexImpl.scala:103)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginIndexImpl.index$lzycompute(PluginIndexImpl.scala:33)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginIndexImpl.index(PluginIndexImpl.scala:22)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginIndexImpl.contains(PluginIndexImpl.scala:49)
[error] 	at org.jetbrains.sbtidea.download.plugin.LocalPluginRegistry.isPluginInstalled(LocalPluginRegistry.scala:44)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginResolver.resolvePluginId(PluginResolver.scala:43)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginResolver.resolve(PluginResolver.scala:22)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginResolver.resolve(PluginResolver.scala:7)
[error] 	at org.jetbrains.sbtidea.download.api.UnresolvedArtifact.resolve(UnresolvedArtifact.scala:9)
[error] 	at org.jetbrains.sbtidea.download.api.UnresolvedArtifact.resolve$(UnresolvedArtifact.scala:9)
[error] 	at org.jetbrains.sbtidea.download.plugin.PluginDependency.resolve(PluginDependency.scala:8)
[error] 	at org.jetbrains.sbtidea.tasks.CreatePluginsClasspath$.$anonfun$apply$1(CreatePluginsClasspath.scala:23)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at org.jetbrains.sbtidea.tasks.CreatePluginsClasspath$.apply(CreatePluginsClasspath.scala:23)
[error] 	at org.jetbrains.sbtidea.Init.$anonfun$projectSettings$6(Init.scala:120)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (coreIntellijSupport / intellijPluginJars) java.nio.file.NoSuchFileException: /Users/deepakkumar/.slinkyPluginIC/sdk/192.6817.14/plugins
[IJ]sbt:slinky> 
```

**Comment by basicobject** [comment]
Fixed by running 
`sbt coreIntellijSupport/updateIntellij` which was mentioned in the readme.
