### ISSUE TITLE
Hot-loading sealed trait - MatchError

### ISSUE THREAD

**Issue by jc776** [shadaj/slinky#38]
When hot-loading code, if I try to match on an old instance of a `sealed trait`, I get a `MatchError`.

[ReactState](https://github.com/jc776/motorcycle/blob/59dfef8f07a289932d118ba1c6603486440d53ca/client/src/main/scala/com/jc776/motorcycle/dev/ReactState.scala)
```scala
object ReactState extends Component {
  type Props = Unit
  sealed trait State
  case object A extends State
  case object B extends State

  class Def(jsProps: js.Object) extends Definition(jsProps) {
    def initialState = A
    
    def render() = {
      state match {
        case A => button("B!!", onClick := {(e: dom.Event) => setState(B)})
        case B => button("A!!", onClick := {(e: dom.Event) => setState(A)}) 
      }
    }
  }
}
```
```
[HMR] Waiting for update signal from WDS...
game-bundle.js:14403 creating proxy
game-bundle.js:735 [HMR] Accepted.
game-bundle.js:62597 [WDS] Hot Module Replacement enabled.
2game-bundle.js:62600 [WDS] App updated. Recompiling...
game-bundle.js:62726 [WDS] App hot update...
game-bundle.js:63154 [HMR] Checking for updates on the server...
0.e46a8a1eea7683d4b3a3.hot-update.js:sourcemap:13665 updating proxy
0.e46a8a1eea7683d4b3a3.hot-update.js:13663 scala.MatchError: A (of class com.jc776.motorcycle.dev.ReactState$A$)
...
game-bundle.js:63156 [HMR] Cannot apply update. Need to do a full reload!
[HMR] Error
    at $c_s_MatchError.webpackHotUpdate../client/target/scala-2.12/motorcycle-client-fastopt.js.$c_jl_Throwable.fillInStackTrace__jl_Throwable (http://localhost:8080/0.e46a8a1eea7683d4b3a3.hot-update.js:6415:14)
...
Navigated to http://localhost:8080/
game-bundle.js:sourcemap:63154 [HMR] Waiting for update signal from WDS...
game-bundle.js:14403 creating proxy
game-bundle.js:735 [HMR] Accepted.
game-bundle.js:62597 [WDS] Hot Module Replacement enabled.
```

HMR is otherwise set up correctly - modifying a component with [simpler state](https://github.com/jc776/motorcycle/blob/59dfef8f07a289932d118ba1c6603486440d53ca/client/src/main/scala/com/jc776/motorcycle/dev/ReactCounter.scala) still works.

This isn't directly a *slinky* problem ([example](https://github.com/jc776/motorcycle/blob/9b54d3d5f19275dbcab0fc6c2cc91f9b004772c8/client/src/main/scala/com/jc776/motorcycle/Main.scala)) but it's a pretty big limitation on what state you can use with *slinky-hot*. Is there a workaround to convert old instances to new ones that could go either in my code or the library?

**Comment by shadaj** [comment]
Thanks for the bug report!

I think this can be solved by slinky. Right now, there are no specialized readers or writers for sealed traits, which causes slinky to just wrap the Scala object when storing the state and cause the problem you are experiencing.

I'll work on adding support for sealed traits to the reader/writer type class derivation macros, which should fix this issue.

**Comment by shadaj** [comment]
@jc776 I've been looking into implementing this, and it's turning out to be quite complicated to handle at the Slinky level in a way that supports all use cases. For now, I recommend manually writing a Reader and Writer for the sealed trait, which Slinky should automatically pick up.

**Comment by jc776** [comment]
Right, that makes sense. Thanks for looking into it!

A simple Reader/Writer doesn't solve it immediately, since the `{__: ...}` state after a `setState` doesn't get re-read before use.
```scala
import scalajs.js 
import org.scalajs.dom

import me.shadaj.slinky.core.Component
import me.shadaj.slinky.web.html._
import me.shadaj.slinky.core.{Writer, Reader}

object ReactSwap extends Component {
  type Props = Unit
  sealed trait State
  case object A extends State
  case object B extends State
  val time = new js.Date()
  implicit val stateWriter: Writer[State] = (inst, root) => {
    println(s"${time} write $inst")
    val str = inst match {
      case A => "A"
      case B => "B"
    }
    js.Dynamic.literal(value = str)
  }
  implicit val stateReader: Reader[State] = (obj, root) => {
    val str = obj.asInstanceOf[js.Dynamic].value.asInstanceOf[String]
    println(s"${time} read ${js.Dynamic.global.JSON.stringify(obj)}")
    str match {
      case "A" => A 
      case "B" => B 
      case _ => throw new Exception("This isn't a serialized State.")
    }
  }

  class Def(jsProps: js.Object) extends Definition(jsProps) {
    def initialState = A
    
    def render() = {
      state match {
        case A => button("B!!", onClick := {(e: dom.Event) => {println("change to B"); setState(B)} })
        case B => button("A!!", onClick := {(e: dom.Event) => {println("change to A"); setState(A)} }) 
      }
    }
  }
}
```
```
creating proxy
sketch-fastopt.js:11853 Sat Sep 23 2017 17:11:23 GMT+0100 (GMT Daylight Time) write A
sketch-fastopt.js:11853 Sat Sep 23 2017 17:11:23 GMT+0100 (GMT Daylight Time) read {"value":"A"}
index.js:425 [HMR] Websocket connection successful.
sketch-fastopt.js:11853 change to B
sketch-fastopt.js:11853 Sat Sep 23 2017 17:11:23 GMT+0100 (GMT Daylight Time) read {"value":"A"}
sketch-fastopt.js:11853 change to A
sketch-fastopt.js:11853 change to B
sketch-fastopt.js:11853 change to A
sketch-fastopt.js:11855 updating proxy
index.js:511 [HMR] Error applying update $c_s_MatchError {s$1: null, e$1: null, stackTrace$1: null, objString$4: null, obj$4: $c_Lcom_jc776_sketch_example_ReactSwap$A$, …}
```

For my uses, serialising out state at the top level isn't too much work:
```scala
import io.circe.Json
import io.circe.syntax._

type Model = ...
type Msg = ...

def update(model: Model, action: Msg): Model = ??? 
def view(model: Model, send: Msg => Unit): ReactElement = ???

val stored = js.Dynamic.global.stored.asInstanceOf[js.UndefOr[Json]].toOption
var state = stored match {
  case None => init
  case Some(json) => json.as[Model]
}

def send(action: Msg): Unit = {
  val next: Model = update(state, action)
  state = next
  js.Dynamic.global.stored = next.asJson.asInstanceOf[js.Dynamic]
  render()
}

val root: dom.Element = dom.document.getElementById("app")
def render(): Unit = {
   ReactDOM.render(program.view(state, send), root)
}
    
render()
```

**Comment by shadaj** [comment]
Ah, that **is** a bug and something I can fix! In the 0.2.0 changes I introduced the __ optimization, but forgot that using that would break hot loading. I'll work on a change to disable the optimization when hot loading is enabled.

**Comment by shadaj** [comment]
@jc776 Can you try with a custom Reader/Writer and the latest snapshot build? I fixed the bug with not using Readers and Writers when hot loading is enabled.

**Comment by jc776** [comment]
Here's a [simpler](https://github.com/jc776/sketch) setup, without the 'server' part.

It's now storing the Reader/Writer values, but reads them with the 'old' Reader after an update, returning old instances of A/B that don't compare:
```java
sketch-fastopt.js:12835 change to B
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) write B
sketch-fastopt.js:12835 {"value":"B"}
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"B"}
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"B"}
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"B"}
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"A"}
sketch-fastopt.js:12837 main()
sketch-fastopt.js:12837 updating proxy
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"B"}
sketch-fastopt.js:12835 Sat Sep 30 2017 22:21:42 GMT+0100 (GMT Daylight Time) read {"value":"B"}
sketch-fastopt.js:12835 scala.MatchError: B (of class com.jc776.sketch.example.ReactSwap$B$)
sketch-fastopt.js:12835   at $c_s_MatchError.$c_jl_Throwable.fillInStackTrace__jl_Throwable(eval at <anonymous> (http://localhost:9966/bundle.js:24503:20), <anonymous>:6097:14)
sketch-fastopt.js:12835   at $c_s_MatchError.$c_jl_Throwable.init___T__jl_Throwable(eval at <anonymous> (http://localhost:9966/bundle.js:24503:20), <anonymous>:6196:8)
sketch-fastopt.js:12835   at scala.MatchError.<init>(eval at <anonymous> (http://localhost:9966/bundle.js:24503:20), <anonymous>:10293:52)
sketch-fastopt.js:12835   at com.jc776.sketch.example.ReactSwap$Def.render(eval at <anonymous> (http://localhost:9966/bundle.js:24503:20), <anonymous>:9843:35)
sketch-fastopt.js:12835   at com.jc776.sketch.example.ReactSwap$Def.render(eval at <anonymous> (http://localhost:9966/bundle.js:24503:20), <anonymous>:9872:14)
sketch-fastopt.js:12835   at com.jc776.sketch.example.ReactSwap$Def.proxiedMethod [as render](http://localhost:9966/bundle.js:55172:30)
sketch-fastopt.js:12835   at {anonymous}()(http://localhost:9966/bundle.js:43471:21)
sketch-fastopt.js:12835   at measureLifeCyclePerf(http://localhost:9966/bundle.js:42751:12)
sketch-fastopt.js:12835   at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext(http://localhost:9966/bundle.js:43470:25)
sketch-fastopt.js:12835   at ReactCompositeComponentWrapper._renderValidatedComponent(http://localhost:9966/bundle.js:43497:32)
index.js:511 [HMR] Error applying update $c_s_MatchError {s$1: null, e$1: null, stackTrace$1: ArrayClass, objString$4: "B (of class com.jc776.sketch.example.ReactSwap$B$)", obj$4: $c_Lcom_jc776_sketch_example_ReactSwap$B$, …}
index.js:514 [HMR] Updated modules (2) ["client\target\scala-2.12\sketch-fastopt.js", "client\index.js"]
```

**Comment by shadaj** [comment]
@jc776 just an update on fixing these issues: Magnolia (https://github.com/propensive/magnolia), the library used by Slinky for deriving instances of Reader and Writer, has received a lot of updates recently that I _think_ will make it possible to fix this issue, so I'm going to update Slinky to use the latest version soon to try and fix these hot-loading bugs.

**Comment by shadaj** [comment]
@jc776 can you try with the changes at https://github.com/shadaj/slinky/pull/45? The latest version of Magnolia allows Slinky to support sealed traits and case objects properly so hot-loading should work now.

**Comment by jc776** [comment]
With `0.1.1+23-0771ecb1`, it's the same as before. The proxy uses the old `StateReader` (printed time 21:50:19 before and after `updating proxy`) which produces an old `A` that fails to match.

After the hot-swap, it should instead read the state with the new code's `StateReader`

It would be better to update the classes/methods in place, instead of this 'old/new' split. [workbench](https://github.com/lihaoyi/workbench) used to be able to do this, but I don't think it works with the new fastOptJS format.

[full log](https://github.com/shadaj/slinky/files/1480414/log-with-hot.txt)

```[HMR] Attempting websocket connection to http://localhost:3123
bundle.js:13322 main()
bundle.js:13322 creating proxy
bundle.js:13322 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) write A
bundle.js:13322 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
bundle.js:24913 [HMR] Websocket connection successful.
sketch-fastopt.js:13309 change to B
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) write B
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"B"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"B"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"B"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 change to A
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) write A
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"B"}
sketch-fastopt.js:13311 main()
sketch-fastopt.js:13311 updating proxy
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 Thu Nov 16 2017 21:50:19 GMT+0000 (GMT Standard Time) read {"value":"A"}
sketch-fastopt.js:13309 scala.MatchError: A (of class com.jc776.sketch.example.ReactSwap$A$)```

**Comment by shadaj** [comment]
Just merged https://github.com/shadaj/slinky/pull/48, which fixes sealed trait hot loading! Thanks so much @jc776 for the detailed logs and reproduction, those were very helpful in fixing this bug!
